[package]
name = "encapfn-mpk"
version = "0.1.0"
edition = "2021"

[features]
default = ["mpkrt_foreign_stack_alloc"]
mpkrt_foreign_stack_alloc = []
mpkrt_heap_alloc_mprotect = []

[build-dependencies]
bindgen = "0.69.4"

[dependencies]
log = "0.4.21"
memfd = "0.6.4"
patchelf = "0.2.1"
tempfile = "3.10.1"

[dependencies.encapfn]
git = "https://github.com/encapfn/encapfn"
rev = "e119560ed64c2ef5bc6e98b5992eeb4db6736e12"
default-features = false
