[workspace]
resolver = "2"
members = [
    "encapfn-mpk",
    "examples/libsodium",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies.encapfn]
git = "https://github.com/encapfn/encapfn"
rev = "91517a0775820b28d85aef28b7ce5d83acdc03ea"
# path = "../encapfn"
features = [ "std" ]

[workspace.dependencies.bindgen]
git = "https://github.com/encapfn/rust-bindgen"
rev = "e10d60a10c23a9ad250b2e280ffc7a8731b0a481"
# path = "../rust-bindgen/bindgen"
